version: "3.7"

services:
  psql:
    image: postgres:16-alpine3.20
    container_name: psql
    env_file:
      - docker.env
    restart: always
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    ports:
      - "172.17.0.1:5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd /app && alembic upgrade head && python3 main.py"
    env_file:
      - .env
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "0.0.0.0:4000:4000"
    depends_on:
      - psql
