version: "3.7"

services:
  psql:
    image: postgres:16-alpine3.20
    container_name: psql
    env_file:
      - docker.env
    restart: always
    ports:
      - "172.17.0.1:5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "0.0.0.0:4000:4000"
    depends_on:
      - psql
